/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  // dangerouslySetInnerHTML 내부 클래스는 content scan이 안 되므로 safelist로 전수 포함
  safelist: [
    // layout
    'flex', 'inline-flex', 'grid', 'hidden', 'block',
    { pattern: /^(flex|inline-flex|grid|hidden|block|absolute|relative|fixed|sticky)/ },
    // sizing
    { pattern: /^w-/ },
    { pattern: /^h-/ },
    { pattern: /^min-/ },
    { pattern: /^max-/ },
    // spacing
    { pattern: /^p-/ },
    { pattern: /^m-/ },
    { pattern: /^px-/ },
    { pattern: /^py-/ },
    { pattern: /^mx-/ },
    { pattern: /^my-/ },
    { pattern: /^gap-/ },
    { pattern: /^space-/ },
    // typography
    { pattern: /^text-/ },
    { pattern: /^font-/ },
    { pattern: /^tracking-/ },
    { pattern: /^leading-/ },
    // background
    { pattern: /^bg-/ },
    // border
    { pattern: /^border-/ },
    { pattern: /^rounded-/ },
    // color / foreground
    { pattern: /^from-/ },
    { pattern: /^via-/ },
    { pattern: /^to-/ },
    // effects
    { pattern: /^shadow-/ },
    { pattern: /^opacity-/ },
    // animation
    { pattern: /^animate-/ },
    { pattern: /^transition-/ },
    { pattern: /^duration-/ },
    { pattern: /^ease-/ },
    // transform
    { pattern: /^transform/ },
    { pattern: /^translate-/ },
    { pattern: /^rotate-/ },
    { pattern: /^scale-/ },
    // state
    { pattern: /^hover:/ },
    { pattern: /^active:/ },
    { pattern: /^data-/ },
    { pattern: /^group/ },
    { pattern: /^peer/ },
    { pattern: /^disabled:/ },
    { pattern: /^aria-/ },
    // responsive
    { pattern: /^sm:/ },
    { pattern: /^md:/ },
    { pattern: /^lg:/ },
    { pattern: /^xl:/ },
    { pattern: /^2xl:/ },
    // arbitrary value
    { pattern: /^\[/ },
    // common named classes used in blip
    'container', 'col-span-1', 'col-span-2', 'col-span-3',
    'row-span-1', 'row-span-2',
    'cursor-pointer', 'overflow-hidden', 'overflow-auto',
    'whitespace-nowrap', 'object-cover', 'object-contain',
    'text-center', 'text-left', 'text-right',
    'items-center', 'items-start', 'items-end', 'justify-between', 'justify-center', 'justify-start', 'justify-end',
    'flex-1', 'flex-col', 'flex-row', 'flex-wrap', 'shrink-0', 'grow-0',
    'z-0', 'z-10', 'z-20', 'z-50', 'z-[1]', 'z-[11]', 'z-[20]', 'z-[998]',
    'inset-0', 'inset-x-0', 'inset-y-0',
    'top-0', 'top-1/2', 'bottom-0', 'left-0', 'right-0',
    '-mt-1', 'mt-0', 'mt-1', 'mt-2', 'mt-3', 'mt-4', 'mt-6', 'mt-8',
    'mb-4', 'mb-10', 'mb-16',
    'ml-[0.38rem]', 'ml-0',
    'mr-4',
    'px-0', 'px-3', 'px-4', 'px-6', 'px-[0.62rem]', 'px-[0.88rem]',
    'py-2', 'py-8', 'py-[0.5rem]', 'py-[0.62rem]',
    'pt-4', 'pt-6',
    'pb-20', 'pb-24', 'pb-[3.25rem]',
    'pl-0', 'pl-[0.62rem]',
    'pr-4', 'pr-8',
    'text-xs', 'text-sm', 'text-[0.8125rem]', 'text-[1.125rem]', 'text-[1.25rem]', 'text-[1.375rem]', 'text-[1.5rem]',
    'text-base', 'text-lg', 'text-xl', 'text-2xl', 'text-3xl',
    'font-medium', 'font-semibold', 'font-bold', 'font-normal',
    'leading-5', 'leading-8', 'leading-[1.125rem]', 'leading-[1.875rem]', 'leading-relaxed',
    'tracking-[-0.025rem]', 'tracking-[-0.4px]',
    'text-white', 'text-white/80',
    'bg-white', 'bg-transparent', 'bg-black/60', 'bg-black/70',
    'bg-gradient-to-r', 'bg-gradient-to-t', 'bg-gradient-to-b',
    'from-white', 'to-transparent', 'from-[#6DB3FF]', 'to-[#B16CFF]',
    'from-cool-gray-900', 'text-white',
    'rounded-md', 'rounded-lg', 'rounded-xl', 'rounded-2xl', 'rounded-full', 'rounded-[inherit]',
    'border', 'border-b', 'border-r', 'border-l',
    'aspect-[2/3]', 'aspect-[23.75/4.375]', 'aspect-[18.75/14.0625]', 'aspect-[248/339.7]',
    'space-y-1', 'space-y-2', 'space-y-4', 'space-x-[0.37rem]',
    'group', 'group/menu-item', 'group/sidebar-wrapper', 'peer',
    'peer/menu-button',
    'focus-visible:ring-2', 'focus-visible:ring-sidebar-ring',
    'ring-sidebar-ring',
    'disabled:pointer-events-none', 'disabled:opacity-50',
    '[&>svg]:pointer-events-none', '[&>svg]:shrink-0', '[&>svg]:size-4', '[&>svg]:size-5', '[&>svg]:size-6',
    '[&>span:last-child]:truncate',
    '[&>*:nth-child(-n+1)]:block', '[&>*:nth-child(-n+2)]:block', '[&>*:nth-child(-n+3)]:block', '[&>*:nth-child(-n+4)]:block',
    'sm:[&>*:nth-child(-n+2)]:block', 'lg:[&>*:nth-child(-n+3)]:block', '2xl:[&>*:nth-child(-n+4)]:block',
    'xl:gap-x-8', '2xl:gap-x-16',
    'lg:p-0', 'lg:px-0', 'lg:px-16', 'lg:pb-24', 'lg:pt-12', 'lg:mb-10', 'lg:mb-16',
    'md:flex', 'md:block', 'md:hidden', 'md:min-h-[28.75rem]',
    'xl:min-h-0', 'xl:hidden', 'xl:block', 'xl:gap-x-8',
    '2xl:basis-2/12', '2xl:grid-cols-4', '2xl:gap-x-16',
    'min-h-0', 'min-h-screen', 'min-h-svh',
    'h-full', 'h-svh', 'h-[2rem]', 'h-[3.125rem]', 'h-[3.625rem]', 'h-[5.625rem]', 'h-[2.25rem]', 'h-[2.7849rem]', 'h-fit', 'h-10', 'h-8', 'h-9',
    'w-full', 'w-fit', 'w-[2.64rem]', 'w-[2.75rem]', 'w-[2.7849rem]', 'w-[3.08rem]',
    'max-w-[120rem]',
    'text-cool-gray-200', 'text-cool-gray-600', 'text-cool-gray-700', 'text-cool-gray-800', 'text-cool-gray-900', 'text-gray-600', 'text-gray-900',
    'bg-cool-gray-50', 'bg-cool-gray-100',
    'border-cool-gray-200',
    'hover:bg-transparent', 'hover:text-white', 'hover:text-accent-foreground', 'hover:bg-accent', 'hover:bg-cool-gray-100', 'hover:bg-black/70',
    'hover:bg-sidebar-accent', 'hover:text-sidebar-accent-foreground',
    'hover:brightness-90', 'hover:scale-110',
    'data-[state=expanded]:bg-sidebar',
    'data-[collapsible=offcanvas]:w-0',
    'data-[collapsible=icon]:w-[--sidebar-width-icon]',
    'data-[collapsible=icon]:!size-8',
    'data-[collapsible=icon]:!p-2',
    'data-[side=right]:rotate-180',
    'data-[side=left]:border-r',
    'data-[side=right]:border-l',
    'group-data-[variant=floating]:rounded-lg',
    'group-data-[variant=floating]:border',
    'group-data-[variant=floating]:border-sidebar-border',
    'group-data-[variant=floating]:shadow',
    'group-data-[collapsible=icon]:overflow-hidden',
    'group-has-[[data-sidebar=menu-action]]/menu-item:pr-8',
    'data-[active=true]:bg-sidebar-accent',
    'data-[active=true]:font-semibold',
    'data-[active=true]:text-sidebar-accent-foreground',
    'data-[state=open]:hover:bg-sidebar-accent',
    'data-[state=open]:hover:text-sidebar-accent-foreground',
    'aria-disabled:pointer-events-none', 'aria-disabled:opacity-50',
    'aria-haspopup', 'aria-expanded', 'aria-controls',
    'role',
    'style',
    'animate-pulse',
    '[&_[data-radix-scroll-area-viewport]]:h-full',
    '[&_[data-radix-scroll-area-viewport]]:w-full',
    '[&_[data-radix-scroll-area-viewport]]:rounded-[inherit]',
  ],
  theme: {
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        sidebar: {
          DEFAULT: 'hsl(var(--sidebar))',
          foreground: 'hsl(var(--sidebar-foreground))',
          border: 'hsl(var(--sidebar-border))',
        },
      },
    },
  },
  plugins: [],
};
